/*
 * File: app/store/TicketViewStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.TicketViewStore', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.TicketPostItemModel'
    ],

    config: {
        model: 'MyApp.model.TicketPostItemModel',
        storeId: 'TicketViewStore',
        proxy: {
            type: 'ajax',
            url: '/test.js',
            reader: {
                type: 'json',
                rootProperty: 'Posts'
            }
        },
        listeners: [
            {
                fn: 'onJsonstoreLoad',
                event: 'load'
            }
        ]
    },

    onJsonstoreLoad: function(store, records, successful, operation, eOpts) {
        var info = Ext.getCmp('ticketSubject');
        var data = store.getProxy().getReader().rawData;
        if (!Ext.isEmpty(data))
        {
            info.setTitle(data.subject);
        }
    }

});