/*
 * File: app/view/TicketInfoPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.TicketInfoPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.TicketInfo',

    config: {
        hideOnMaskTap: true,
        modal: true,
        hideAnimation: {
            type: 'slideOut',
            duration: 1000,
            direction: 'down'
        },
        showAnimation: {
            type: 'slideIn',
            duration: 1000,
            direction: 'up'
        },
        tpl: [
            '<div class=\'ticketInfo\'>',
            '	<div class="pf_item">',
            '		<div class="label">公司名称</div>',
            '        <div class="con">{companyName}</div>',
            '	</div>',
            '	<div class="pf_item">',
            '		<div class="label">工单标题</div>',
            '        <div class="con">{subject}</div>',
            '	</div>',
            '	<div class="pf_item">',
            '		<div class="label">发起人</div>',
            '        <div class="con">{fromUserName}</div>',
            '	</div>',
            '	<div class="pf_item">',
            '		<div class="label">受理人</div>',
            '        <div class="con">{assigneeUserName}</div>',
            '	</div>',
            '    <tpl if="!Ext.isEmpty(joinUserName)">',
            '        <div class="pf_item">',
            '            <div class="label">抄送</div>',
            '            <div class="con">{joinUserName}</div>',
            '        </div>',
            '	</tpl>',
            '	<div class="pf_item">',
            '		<div class="label">状态</div>',
            '        <div class="con">{status}</div>',
            '	</div>',
            '	<div class="pf_item">',
            '		<div class="label">创建时间</div>',
            '        <div class="con">{creatTime:timeAgoInWords}</div>',
            '	</div>',
            '	<div class="pf_item">',
            '		<div class="label">到期时间</div>',
            '        <div class="con">{hopeDoneTime:timeAgoInWords}</div>',
            '	</div>',
            '</div>'
        ]
    }

});