/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({
    paths: {
        'Ext.ux': '/touch/src/ux',
        Ext: '/touch/src'
    }
});

Ext.application({

    requires: [
        'Ext.ux.Fileup'
    ],
    models: [
        'TicketPostItemModel'
    ],
    stores: [
        'TicketViewStore'
    ],
    views: [
        'MyContainer',
        'TicketInfoPanel'
    ],
    controllers: [
        'MyController'
    ],
    name: 'MyApp',

    launch: function() {
        Ext.util.Format.timeAgoInWords = function(date) {
            try {
                var now = Math.ceil(Number(new Date()) / 1000),
                    dateTime = Math.ceil(Number(new Date(date)) / 1000),
                    diff = now - dateTime,
                    str;

                if (diff < 60) {
                    return String(diff) + ' 秒钟前';
                } else if (diff < 3600) {
                    str = String(Math.ceil(diff / (60)));
                    return str +  '分钟前';
                } else if (diff < 86400) {
                    str = String(Math.ceil(diff / (3600)));
                    return str +  '小时前';
                } else if (diff < 60 * 60 * 24 * 365) {
                    return date;
                } else {
                    return date;
                }
            } catch (e) {
                return '';
            }
        };


        var ticketViewStore = Ext.getStore("TicketViewStore");
        if ("undefined" != typeof ticketId)
        { 
            ticketViewStore.getProxy().setUrl('/Ticket/DetailsJson/' + ticketId);
            Ext.onReady(function(){
                MyApp.controller.MyController.refreshReply();
            });
        }
        ticketViewStore.load();


        Ext.create('MyApp.view.MyContainer', {fullscreen: true});
    }

});
