/*
 * File: app/controller/MyController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.MyController', {
    extend: 'Ext.app.Controller',

    statics: {
        replyMessage: function(message, fn) {
            Ext.Ajax.request({
                url: '/Ticket/Details/' + ticketId,
                params: {
                    message: message
                },
                success: function(response){ 
                    var text = Ext.decode(response.responseText); 
                    fn(text);     

                },
                failure: function(response){
                    Ext.Msg.alert('添加失败');
                }
            });
        },

        refreshReply: function() {
            Ext.Ajax.request({
                url: '/Comet/GetMessage' ,
                method:'POST',
                params: {
                    ticketId: ticketId
                },
                success: function(response){ 
                    var text = Ext.decode(response.responseText); 
                    var store = Ext.getStore('TicketViewStore');
                    store.add(text);
                    var ticketView =Ext.getCmp('TicketView');
                    ticketView.getScrollable().getScroller().scrollToEnd(true);  
                    MyApp.controller.MyController.refreshReply();
                },
                failure: function(response){
                    MyApp.controller.MyController.refreshReply();
                }
            });
        }
    },

    config: {
    }
});